events {}

http {
    client_max_body_size 20M;

    server {
        listen 80;
        # server_name domena.pl;

        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /photos/ {
            proxy_pass http://minio:9000/photos/;
            proxy_set_header Host minio:9000;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
